test 3

diff --git a/.github/workflows/Sync_DDL_scripts.yml b/.github/workflows/Sync_DDL_scripts.yml
--- a/.github/workflows/Sync_DDL_scripts.yml
+++ b/.github/workflows/Sync_DDL_scripts.yml
@@ -95,11 +95,11 @@ jobs:
                 formatted_table_name=$(echo "$full_table_name" | sed -e 's/\./\".\"/g')
               fi
 
-                if [ -n "$formatted_table_name" ]; then
-                    echo "Dropping table $formatted_table_name if it exists"
-                    psql -c "DROP TABLE IF EXISTS $formatted_table_name CASCADE"
-                else
-                    echo "Could not extract table name from $file"
-                    exit 1
-                fi
+              if [ -n "$formatted_table_name" ]; then
+                  echo "Dropping table $formatted_table_name if it exists"
+                  psql -c "DROP TABLE IF EXISTS $formatted_table_name CASCADE"
+              else
+                  echo "Could not extract table name from $file"
+                  exit 1
+              fi
           shell: bash
